customer sales 2=

SUMX('Product Lookup',
RELATEDTABLE('Sales by Store'),
'Sales by Store'[unit_price] * 'Sales by Store'[quantity_sold]

)

)



customer sales 3=

SUMX(

VALUES('Product Lookup'),

SUMX('Sales by Store',

if(

'Product Lookup'[product_id]= 'sales by store'[product_id]],
'Sales by Store'[quantity_sold] * 'Sales by Store'[unit_price],

)

)

)

---------------------------------------------------