customer sales 2=

SUMX('Product Lookup',
RELATEDTABLE('Sales by Store'),
'Sales by Store'[unit_price] * 'Sales by Store'[quantity_sold]

)

)



customer sales 3=

SUMX(

VALUES('Product Lookup'),

SUMX('Sales by Store',

if(

'Product Lookup'[product_id]= 'sales by store'[product_id]],
'Sales by Store'[quantity_sold] * 'Sales by Store'[unit_price],

)

)

)

---------------------------------------------------
Average Daily Sales (AVERAGEX) = 
AVERAGEX(
    'Calendar',
    [Customer Sales]
)


------------------------------------------------------------
Moving Average (AVERAGEX) = 
VAR LastTransactionDate = MAX('Calendar'[Transaction_Date])
VAR AverageDay = 30
VAR PeriodInVisual = 
FILTER(
    ALL(
        'Calendar'[Transaction_Date]
    ),
    AND(
        'Calendar'[Transaction_Date] > LastTransactionDate - AverageDay,
        'Calendar'[Transaction_Date] <= LastTransactionDate
    )
)
VAR OutPut =
CALCULATE(
    AVERAGEX(
        'Calendar',
        [Customer Sales]
    ),
    PeriodInVisual
)
RETURN
OutPut

------------------------------------------------------
Rank of Customer Sales (RANKX) = 
IF(
    HASONEVALUE(
        'Product Lookup'[product_category]
    ),
    RANKX(
        ALL(
            'Product Lookup'[product_category]
        ),
        [Customer Sales]
    )
)

-----------------------------------------------------------
Rank of Rounded Customer Sales (RANKX) = 
IF(
    HASONEVALUE(
        'Product Lookup'[product_category]
    ),
    RANKX(
        ALL(
            'Product Lookup'[product_category]
        ),
        [Rounded Customer Sales],
        ,DESC
        ,Skip
    )
)
------------------------------------------------------------------------
Sales by Employee Name (CONCATENATEX) = 
IF(
    HASONEVALUE(
        'Employee Lookup'[first_name]
    ),
    "Employee: " &
    CONCATENATEX(
        VALUES(
            'Employee Lookup'[first_name]
        ),
        'Employee Lookup'[first_name] &
        "-" &
        FORMAT([% of Customer Sales (CONCATENATEX Assignment)], "Percent"),
        ", ",
        'Employee Lookup'[first_name],
        ASC
    ),
    "Select a Single Employee"
)
-------------------------------------------------------------------
Selected Product Category (CONCATENATEX) = 
"Showing Sales For: " &
CONCATENATEX(
    VALUES(
        'Product Lookup'[product_category]
    ),
    'Product Lookup'[product_category],
    ", ",
    'Product Lookup'[product_category],
    ASC
)----
--------------------------------------------------------------------------