customer sales 2=

SUMX('Product Lookup',
RELATEDTABLE('Sales by Store'),
'Sales by Store'[unit_price] * 'Sales by Store'[quantity_sold]

)

)



customer sales 3=

SUMX(

VALUES('Product Lookup'),

SUMX('Sales by Store',

if(

'Product Lookup'[product_id]= 'sales by store'[product_id]],
'Sales by Store'[quantity_sold] * 'Sales by Store'[unit_price],

)

)

)

---------------------------------------------------
Average Daily Sales (AVERAGEX) = 
AVERAGEX(
    'Calendar',
    [Customer Sales]
)


------------------------------------------------------------
Moving Average (AVERAGEX) = 
VAR LastTransactionDate = MAX('Calendar'[Transaction_Date])
VAR AverageDay = 30
VAR PeriodInVisual = 
FILTER(
    ALL(
        'Calendar'[Transaction_Date]
    ),
    AND(
        'Calendar'[Transaction_Date] > LastTransactionDate - AverageDay,
        'Calendar'[Transaction_Date] <= LastTransactionDate
    )
)
VAR OutPut =
CALCULATE(
    AVERAGEX(
        'Calendar',
        [Customer Sales]
    ),
    PeriodInVisual
)
RETURN
OutPut

------------------------------------------------------
