/* Related, UserRelationahip, TreatAS , RelatedTable etc */

Product Group=
RELATED('Product Lookup'[product_group]

)



wholesale cost=

SUMX(


'Sales by Store',

'Sales by Store'[quantity_sold] * related('Product Lookup'[current_wholesale_price])



-- RelatedTable( Only returns expression for records with relation)

Number of Food Items Made=

SUMX(

RELATEDTABLE('Food Inventory'),

'Food Inventory'[quantity_start_of_day]
)



--UserRelationship ( Realtionship between Two Evwen when Inactive)
Quantity Sold=

CALCULATE(
[SUM Quantity Sold],
USERELATIONSHIP(
'Food Inventory'[baked_date],'Calendar'[Transaction_Date])





-- Cross Filter ( Remember filter direction can be one,  both, none)
Number of Employee=
CALCULATE(
COUNTROWS(
VALUES(
'Employee Lookup')
),

CROSSFILTER(

'Sales by Store'[staff_id],
'Employee Lookup'[staff_id],
BOTH
))


-- Treat AS


treatas Demo=
var storedid=
{"1",
"2",
"3"
}


RETURN

TREATAS(
storeid,
'Store Lookup'[store_id]
)


-------------------------------sun beans but create a virtual reltionship bwtween calaenda =r and union demo using the calendar and month  name for  both tables
Bean Goal (TREATAS) = 
CALCULATE(
    SUM(
        'UNION Demo'[Bean/Teas Goal]
    ),
    TREATAS(
        VALUES(
            'Calendar',
            'Calendar'[Year_ID]),
            'UNION Demo'[Year]
        ),
        treatas(VALUES(
        
        'Calendar'[Month_Name]),
        'UNION Demo'[Month]
    )
    )
)


---------------------------------
Beverage Goal (TREATAS) = 
CALCULATE(
    SUM(
        'UNION Demo'[Beverage Goal]
    ),
    TREATAS(
        SUMMARIZE(
            'Calendar',
            'Calendar'[Year_ID],
            'Calendar'[Month_Name]
        ),
        'UNION Demo'[Year],
        'UNION Demo'[Month]
    )
)