
--### Distinctcount
Total Customers=DISTINCTCOUNT(

'CUSTOMER LOOKUP'[CUSTOMERID]
)



---Countrows ( Use count rows with values)

TOTAL EMPLOYEES=COUNTROWS(

VALUES( 
'EMPLOYEE LOOKUP'
        )

)



-- SUM AND SUMX ( syntax sugar is when you write a sum functions and DAX uses the iterator function to execute in the backend, NB : not only sum but all aggregrate functions)

TOTAL SALES= SUM(

'SALES BY STORE'[QUANTITY SOLD]

)



TOTAL SALES2= SUMX(

'SALES BY STORE','SALES BY STORE'[QUANTITY SOLD]
)



-- INT

INT(3.124)


--ROUNDUP
ROUND(3.12438,2) = 3.13


--ROUNDDOWN
ROUND(3.12438,2) = 3.12



--FIXED ( VWRY USEFUL WHEN YOU CONVERTING A NUMBER TO TEXT)
FIXED(3.12438,2) ==3.12


--MROUND IN TIME VALUE
MROUND(9:34:15,0:15) == 9:30:00 ( ROUNDS THE MINUTE UP OR DOWN BY THE MINUTE COMPONENT)


FLOOR(9:34:15,0:15) == 9:30:00 ( ROUNDS THE MINUTE COMPONENT TO THE NEAREST MULTIPLE)
































