/* TAble Joins */

cross join demo=
CROSSJOIN(
VALUES('Product Lookup'[product_category]
),

values('Product Lookup'[product_group]
),

FILTER(VALUES(
'Store Lookup',

'Store Lookup'[store_id]=3
)
)


-- Union

Union Demo=

union('Target Sales - April 2019 (DATATABLE)',

'Target Sales - March 2019 (DATATABLE)'

)



--Except

except demo=

EXCEPT(

'Customer Lookup',

FILTER(
'Customer Lookup',
'Customer Lookup'[customer_since] > DATE((2017,02,01)



--or

except demo=

EXCEPT(

'Customer Lookup',

FILTER(VALUES(
,
'Customer Lookup'[customer_since] > DATE((2017,02,01)
)




---- Intersect
New'New Employees (INTERSECT)'=

INTERSECT(

ADDCOLUMNS(

'Employee Lookup',

"Revenue",

[Customer Sales]
),

ADDCOLUMNS(
FILTER(
'Employee Lookup',
'Employee Lookup'[start_date] > DATE(2016,12,13)),
"Revenue",

[Customer Sales]
)
)






































